apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-rc
spec:
   replicas: 3
   selector: 
     app: jenkins-pod
     version: 2.7.1
   template:
     metadata:
       labels:
          app: jenkins-pod 
          version: 2.7.2
     spec:
        containers:
        - name: jenkins-container   
          image: jenkins:2.60.3 
          ports:
          - containerPort: 8080  